// flow-typed signature: 19e65ad11d051bbc3408fc53f69be1e2
// flow-typed version: <<STUB>>/react-native-fontawesome_v^5.7.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fontawesome'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fontawesome' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fontawesome/FontAwesomeIcons' {
  declare module.exports: any;
}

declare module 'react-native-fontawesome/Icon' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fontawesome/FontAwesomeIcons.js' {
  declare module.exports: $Exports<'react-native-fontawesome/FontAwesomeIcons'>;
}
declare module 'react-native-fontawesome/Icon.js' {
  declare module.exports: $Exports<'react-native-fontawesome/Icon'>;
}
