// flow-typed signature: a6baea3a98e675f2f644da87d3beea91
// flow-typed version: <<STUB>>/react-native-storybook-loader_v^1.8.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-storybook-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-storybook-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-storybook-loader/src/constants' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/constants.test' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/logger' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/logger.test' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/paths/cliResolver' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/paths/cliResolver.test' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/paths/multiResolver' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/paths/multiResolver.test' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/rnstl-cli' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/storyFinder/index' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/storyFinder/index.test' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/storyWriterProcess' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/storyWriterProcess.test' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/utils/pathHelper' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/utils/pathHelper.test' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/utils/testUtils' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/writer/index' {
  declare module.exports: any;
}

declare module 'react-native-storybook-loader/src/writer/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-storybook-loader/src/constants.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/constants'>;
}
declare module 'react-native-storybook-loader/src/constants.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/constants.test'>;
}
declare module 'react-native-storybook-loader/src/logger.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/logger'>;
}
declare module 'react-native-storybook-loader/src/logger.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/logger.test'>;
}
declare module 'react-native-storybook-loader/src/paths/cliResolver.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/paths/cliResolver'>;
}
declare module 'react-native-storybook-loader/src/paths/cliResolver.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/paths/cliResolver.test'>;
}
declare module 'react-native-storybook-loader/src/paths/multiResolver.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/paths/multiResolver'>;
}
declare module 'react-native-storybook-loader/src/paths/multiResolver.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/paths/multiResolver.test'>;
}
declare module 'react-native-storybook-loader/src/rnstl-cli.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/rnstl-cli'>;
}
declare module 'react-native-storybook-loader/src/storyFinder/index.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/storyFinder/index'>;
}
declare module 'react-native-storybook-loader/src/storyFinder/index.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/storyFinder/index.test'>;
}
declare module 'react-native-storybook-loader/src/storyWriterProcess.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/storyWriterProcess'>;
}
declare module 'react-native-storybook-loader/src/storyWriterProcess.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/storyWriterProcess.test'>;
}
declare module 'react-native-storybook-loader/src/utils/pathHelper.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/utils/pathHelper'>;
}
declare module 'react-native-storybook-loader/src/utils/pathHelper.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/utils/pathHelper.test'>;
}
declare module 'react-native-storybook-loader/src/utils/testUtils.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/utils/testUtils'>;
}
declare module 'react-native-storybook-loader/src/writer/index.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/writer/index'>;
}
declare module 'react-native-storybook-loader/src/writer/index.test.js' {
  declare module.exports: $Exports<'react-native-storybook-loader/src/writer/index.test'>;
}
